### ISSUE TITLE
05 script bug

### ISSUE THREAD

**Issue by ngiangre** [rahulremanan/python_tutorial#1]
<img width="1440" alt="screen shot 2017-08-14 at 11 26 55 am" src="https://user-images.githubusercontent.com/7811531/29278737-a0190ba2-80e3-11e7-93d1-8e4b8309b5ba.png">

Idk if we're going to try to get the script working through and through for next weekend. If we are, here's a bug I have running the script. Let me know what you want to do or what I should do.

**Comment by rahulremanan** [comment]
To fix the model saving issue:  TypeError: a bytes-like object is required, not 'str' due to line 214 code: file._write(ltsm.to_json()), please use the most recent revision of the code from Github using git clone or git pull.
