### ISSUE TITLE
06_QA_Demo_mac.py

### ISSUE THREAD

**Issue by ngiangre** [rahulremanan/python_tutorial#2]
The original 06_QA_Demo.py needed a mac analog so I added the file named in the header which added in the line 155-starting try/except block at line 162:

from os.path import expanduser
home = expanduser("~")
tar = tarfile.open(home+'/GitHub/python_tutorial/NLP/data/babi_tasks_1-20_v1-2.tar.gz')

This should run with `python 06_QA_Demo_mac.py` on any mac.

**Comment by rahulremanan** [comment]
This is not an issue and more of a feature request. A parser for command line arguments is in the works. For now, just edit the file and folder pointers to point to the correct file location.
